version: '3'

services:
  ipfs:
    container_name: ipfs-host
    image: ipfs/go-ipfs
    ports:
      - "4001:4001"
      - "127.0.0.1:5001:5001"
      - "8080:8080"
  ganache:
    container_name: ganache4dev
    image: trufflesuite/ganache-cli
    command: --mnemonic 'candy maple cake sugar pudding cream honey rich smooth crumble sweet treat' --debug --verbose --db /data --deterministic
    restart: always
    volumes:
    - ./ganache4dev:/data
    ports:
    - "8545:8545"
