version: '3'

services:
  ipfs:
    image: jbenet/go-ipfs:latest
    ports:
      - "4001:4001"
      - "127.0.0.1:5001:5001"
      - "8080:8080"
  ganache:
    container_name: dev_ganache
    image: trufflesuite/ganache-cli
    command: --mnemonic 'candy maple cake sugar pudding cream honey rich smooth crumble sweet treat' --debug --verbose --networkId 7777 --db /data --deterministic
    restart: always
    volumes:
    - ./dev_ganache:/data
    ports:
    - "8545:8545"